- name: Enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^PasswordAuthentication yes"
    line: "PasswordAuthentication no"

- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#PermitRootLogin yes"
    line: "PermitRootLogin no"

- name: Enable SSH key authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#PubkeyAuthentication yes"
    line: "PubkeyAuthentication yes"

- name: Change SSHD port
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#Port 22"
    line: "Port {{ sshd_port }}"

- name: Allow the new SSHD port through the firewall / Ansible needs to use this port for operating the node machine
  firewalld:
    port: "{{ sshd_port }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes

- name: Copy firewall settings file from '/usr/lib/firewalld/services/ssh.xml' to '/etc/firewalld/services/ssh.xml'
  copy:
    src: /usr/lib/firewalld/services/ssh.xml
    dest: /etc/firewalld/services/ssh.xml
    remote_src: yes
    owner: root
    group: root
    mode: 0600

- name: Apply new SSHD port settings to '/etc/firewalld/services/ssh.xml'
  replace:
    path: /etc/firewalld/services/ssh.xml
    regexp: 'port="22"'
    replace: "port=\"{{ sshd_port }}\""

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Wait for sshd stopped
  become: False 
  local_action: wait_for
  args:
    host: '{{ ansible_host }}'
    port: 22
    state: stopped

- name: Wait for sshd started
  become: False 
  local_action: wait_for
  args:
    host: '{{ ansible_host }}'
    port: '{{ sshd_port }}'
    state: started
    delay: 15
